export const data = [
  {
    id: '1',
    name: 'IT',
    isChecked: false,
    isIndeterminate: false,
    count: 133,
    children: [
      {
        id: '4',
        name: '데이터',
        isChecked: false,
        isIndeterminate: false,
        count: 24,
        children: [],
      },
      {
        id: '5',
        name: '소프트웨어/앱/웹',
        isChecked: false,
        isIndeterminate: false,
        count: 76,
        children: [
          {
            id: '11',
            name: '소프트웨어',
            isChecked: false,
            isIndeterminate: false,
            count: 47,
            children: [],
          },
          {
            id: '12',
            name: '앱',
            isChecked: false,
            isIndeterminate: false,
            count: 13,
            children: [],
          },
          {
            id: '13',
            name: '웹',
            isChecked: false,
            isIndeterminate: false,
            count: 16,
            children: [],
          },
        ],
      },
      {
        id: '6',
        name: '솔루션/SaaS/보안',
        isChecked: false,
        isIndeterminate: false,
        count: 33,
        children: [],
      },
    ],
  },
  {
    id: '2',
    name: '금융',
    isChecked: false,
    isIndeterminate: false,
    count: 23,
    children: [
      {
        id: '7',
        name: '보험/대출',
        isChecked: false,
        isIndeterminate: false,
        count: 21,
        children: [
          {
            id: '14',
            name: '보험',
            isChecked: false,
            isIndeterminate: false,
            count: 2,
            children: [],
          },
          {
            id: '15',
            name: '대출',
            isChecked: false,
            isIndeterminate: false,
            count: 19,
            children: [],
          },
        ],
      },
      {
        id: '8',
        name: '암호화폐',
        isChecked: false,
        isIndeterminate: false,
        count: 2,
        children: [],
      },
    ],
  },
  {
    id: '3',
    name: '농축수산업',
    isChecked: false,
    isIndeterminate: false,
    count: 11,
    children: [
      {
        id: '9',
        name: '농축수산업',
        isChecked: false,
        isIndeterminate: false,
        count: 10,
        children: [
          {
            id: '16',
            name: '농업',
            isChecked: false,
            isIndeterminate: false,
            count: 2,
            children: [],
          },
          {
            id: '17',
            name: '축산업',
            isChecked: false,
            isIndeterminate: false,
            count: 0,
            children: [],
          },
          {
            id: '18',
            name: '수산업',
            isChecked: false,
            isIndeterminate: false,
            count: 4,
            children: [],
          },
        ],
      },
      {
        id: '10',
        name: '기타',
        isChecked: false,
        isIndeterminate: false,
        count: 1,
        children: [],
      },
    ],
  },
];